# Generated by Django 4.2 on 2023-04-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.TextField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('genres', models.JSONField()),
            ],
        ),
    ]
